### ISSUE TITLE
Handle review comments from DRF

### ISSUE THREAD

**Issue by Archmonger** [em1208/adrf#1]
There's a few review comments on the [DRF PR](https://github.com/encode/django-rest-framework/pull/8617) that never got marked as completed. For example, support for async fields on serializers.

Mark them as completed over there if needed, or create issues on this repo to handle those tasks.

**Comment by em1208** [comment]
I would like to add async support to serializers and mixins. Is there anything else?

**Comment by Archmonger** [comment]
- https://github.com/encode/django-rest-framework/pull/8617#discussion_r974706589
- https://github.com/encode/django-rest-framework/pull/8617#discussion_r960002873
- https://github.com/encode/django-rest-framework/pull/8617#issuecomment-1250210103
   - The comment above encompasses the following....
   - https://github.com/encode/django-rest-framework/issues/8655
   - https://github.com/encode/django-rest-framework/issues/8656
   - https://github.com/encode/django-rest-framework/issues/8657

**Comment by em1208** [comment]
@Archmonger Thanks a lot for the comment. The exceptions in the Django admin and when clicking the OPTIONS button are fixed already. The only problem left is making an async version of the serializer since the one in DRF needs to be wrapped with `sync_to_async` for it to work.

**Comment by DhruvaPatil98** [comment]
Hey, is there any update on adding async support for serializers?

**Comment by Archmonger** [comment]
Looks like the answer is nope. But, it should be a fairly simple contribution.

@DhruvaPatil98 Would you be willing to PR this?

**Comment by em1208** [comment]
PR https://github.com/em1208/adrf/pull/17 has been merged which add support for async serializers.
