### ISSUE TITLE
Does `adrf` support `django`(version 4.2)?

### ISSUE THREAD

**Issue by lilli-nishikawa** [em1208/adrf#12]
According to README.md, the Requirements are Python 3.8+ and Django 4.1. 

However, the Async Views section says:
>When using Django 4.1 and above, this package allows you to work with async class and function based views.

So, I have a question about: 

Does `adrf` support `django`(version 4.2)?

**Comment by imgVOID** [comment]
I recently tried and it seems to work

**Comment by em1208** [comment]
Yes, `adrf` supports Django 4.2 and I just updated the tox configuration to show that.
