### ISSUE TITLE
how can i write async serializers to go with my async ViewSet?

### ISSUE THREAD

**Issue by ehudkaldor** [em1208/adrf#13]
this framework looks very interesting in the sense of turning my DRF application to async. the snag i am running into right now is how to serialize the data.

the example on the README use direct fields from the models. is there a way to make a serializer in, that would not through an error about not being sync or corotines not being serializable, or is it necessary to manually serialize every model?

something along:
```
class AsyncViewSet(ViewSet):

    async def list(self, request):
        users_list = []
        async for user in User.objects.all():
            s = await UserSerializer(user, many=False)
            users_list.append(s.data)
        return Response(user_list)

    async def retrieve(self, request, pk):
        user = await User.objects.filter(pk=pk).afirst()
        s = await UserSerializer(user, many=False)
        return Response(user)
```

**Comment by em1208** [comment]
PR https://github.com/em1208/adrf/pull/17 has been merged with support for async serializers.
