### ISSUE TITLE
ViewSet incorrectly checks if ordinary properties and members on a class are async

### ISSUE THREAD

**Issue by dalberto** [em1208/adrf#14]
I configured a viewset to include a `content_negotiation_class`, as follows:

```py
from adrf.viewsets import ViewSet as AsyncViewSet

class MyViewSet(AsyncViewSet):
    content_negotiation_class = MyContentNegotiation
    
    ...
```

And the viewset fails with:

```
django.core.exceptions.ImproperlyConfigured: MyViewSet action handlers must either be all sync or all async.
````

I confirmed it's because this check is too coarse and including non-callable members.

https://github.com/em1208/adrf/blob/153b89c221b205dd3036d50690b667a39d201845/adrf/viewsets.py#L147

I quickly attempted to override and perform a more precise check to no avail. I think checking `isinstance(function, types.FunctionType)` is promising but adding it on it's own was not enough.

My workaround is to override `view_is_async` in the viewset to return `True` and just be very careful.

**Comment by aaaaaaaalesha** [comment]
Yes... I have one more callable objects in the attributes of my AsyncViewSet, for example this serializer:
```python
class BoardsViewSet(ViewSet):
    serializer_class = BoardListSerializer
```
But this check in `view_is_async` classproperty looks sad for not-a-toy projects.
```python
    def view_is_async(cls):
        """
        Checks whether viewset methods are coroutines.
        """
        result = [
            asyncio.iscoroutinefunction(function)
            for name, function in cls.__dict__.items()
    ->      if callable(function) and not name.startswith("__")
        ]
        # ...
```

**Comment by sarayourfriend** [comment]
To clarify the issue description, classes _are_ callable objects in Python and will pass the isinstance check against the function type.

A potential solution is to limit the check to the DRF generic view function names (`list`, `get`, `post`, etc), and additionally checking anything wrapped with `@action` (maybe by checking for the properties `action` adds like `url_path` and `url_name`, still potentially flaky though).
