### ISSUE TITLE
caching issue

### ISSUE THREAD

**Issue by olupy** [em1208/adrf#16]
the traditional caching feature on django/ drf is not compatible with adrf

**Comment by olupy** [comment]
the trace back error message is        AttributeError: 'coroutine' object has no attribute 'streaming'

**Comment by em1208** [comment]
Hi @olupy, are you able to provide a failing test for this issue? Thanks!

**Comment by captain828** [comment]
This is a known issue with Djang 4.2 not supporting `async` on cache decorators and is fixed in Django 5.0.

**Comment by robd003** [comment]
> This is a known issue with Djang 4.2 not supporting `async` on cache decorators and is fixed in Django 5.0.

Any word on if there was a backported fix for this? I'm trying to stay on LTS releases only for Django...

**Comment by robd003** [comment]
> This is a known issue with Djang 4.2 not supporting `async` on cache decorators and is fixed in Django 5.0.

@captain828 Any word on if there was a backported fix for this? I'm trying to stay on LTS releases only for Django...

**Comment by captain828** [comment]
Not that I know of.
If you need to stay on 4.2 LTS, create a new decorator with the 5.0 code.

**Comment by em1208** [comment]
Closing since this issue is fixed on Django 5.0.

**Comment by alejoar** [comment]
This is still happening with async actions
