### ISSUE TITLE
Authentication error with 0.1.3 release 

### ISSUE THREAD

**Issue by XiweiAtVian** [em1208/adrf#28]
REST API interface GET access as "GET /services/p/p/" got complain :
```
{
    "detail": "Authentication credentials were not provided."
}
```

Here is the setup of view and URL conf
```
from adrf.views import APIView as AsyncAPIView
@authentication_classes([authentication.SessionAuthentication, ExpiringTokenAuthentication])
@permission_classes([permissions.IsAuthenticated])
class DummyView(AsyncAPIView):
    async def get(self, request, category, slug): pass 
```

```
path('services/<str:category>/<str:slug>/', DummyView.as_view()
```

It's fine with 0.1.2, but starts fail with 0.1.3.

**Comment by em1208** [comment]
@XiweiAtVian Can you please try:
```python
class DummyView(AsyncAPIView): 
    authentication_classes = [authentication.SessionAuthentication, ExpiringTokenAuthentication]
    permission_classes = [permissions.IsAuthenticated]
    async def get(self, request, category, slug): pass 
```
instead of using the decorators and see if it makes any difference? Thanks!

**Comment by ntsphwoelfel** [comment]
> @XiweiAtVian Can you please try:
> 
> ```python
> class DummyView(AsyncAPIView): 
>     authentication_classes = [authentication.SessionAuthentication, ExpiringTokenAuthentication]
>     permission_classes = [permissions.IsAuthenticated]
>     async def get(self, request, category, slug): pass 
> ```
> 
> instead of using the decorators and see if it makes any difference? Thanks!

I'm using that version and got the same problem. (I assume `authentication` is `from rest_framework import authentication`) Reverted back to 0.1.2 and that works again.

**Comment by SilverFoxA** [comment]
+1

I'm using the latest version with my existing application and I found the same error.

**Comment by mliudev** [comment]
I have the same issue and it appears that the `request.user` attribute is lost somewhere along the way. I put a breakpoint in `rest_framework.authentication.SessionAuthentication` and inspected the user object but it was empty.

**Comment by Crazy0416** [comment]
@mliudev I found the location where `request.user` was lost.
I use adrf's `APIView`. This class has `initialize_request` method, this method override origin `request` instance and return new `request` instance

**Comment by mliudev** [comment]
> @mliudev I found the location where `request.user` was lost. I use adrf's `APIView`. This class has `initialize_request` method, this method override origin `request` instance and return new `request` instance

This is overriding DRF's initialize_request with an `AsyncRequest` instead of a sync request:

- https://github.com/em1208/adrf/blob/0.1.4/adrf/requests.py#L9
- https://github.com/encode/django-rest-framework/blob/3.14.0/rest_framework/views.py#L385

The AsyncRequest wraps DRF's Request with `async_to_sync` helpers. The user is probably being lost somewhere in here. I just don't know why or how.

**Comment by em1208** [comment]
Thanks @mliudev for looking into this. I just released version `0.1.5` which should fix this issue.

**Comment by mliudev** [comment]
Thanks for this! Will test and let you know how it goes.

**Comment by mliudev** [comment]
It works!
