### ISSUE TITLE
Question ? 🙋🏼‍♂️

### ISSUE THREAD

**Issue by enzofrnt** [em1208/adrf#41]
Hello,

I actively participate as a contributor in the development of the [django eventstream module](https://github.com/fanout/django-eventstream), and I developed the DRF part of the module. My question is: what could be the benefit of adding ADRF support to this module? What can the async APIView bring, given that SSE is asynchronous?

Thank you.

**Comment by em1208** [comment]
Hello @enzofrnt, I think you should be able to use `adrf` serializers and viewset with `django-eventstream` and make it async. I just looked at the code of eventstream and you can implement the `channel` action of `EventsViewSet` with `adrf`. Please report back if you face any issue.

**Comment by enzofrnt** [comment]
I'm not using any kind of serializer and i'm going to replace the ViewSet by an APIView.
The only things that u want to know is what implementation of AsyncAPIView can provide to us.
Thanks you !

**Comment by em1208** [comment]
I'm not sure I fully understand your question but you can replace APIView with the async APIView implementation provided by `adrf` and it will work as long as you implement it following the docs. I hope this helps!

**Comment by enzofrnt** [comment]
But is there any benefit to adding the asynchronous version ?

**Comment by em1208** [comment]
Yes, you should see some benefits. Async django is more efficient that sync on certain use cases. The benefits you will see depends on your application. I suggest you to implement both async and sync and see what works best for you.

**Comment by enzofrnt** [comment]
We could let user choice I think, but by putting preference on async.
Did you think how I can verify which is more efficient ?

**Comment by em1208** [comment]
Sounds good. You can test both implementations and see which works best.
