### ISSUE TITLE
Wrong handlers being found for ViewSets

### ISSUE THREAD

**Issue by tbeadle** [em1208/adrf#44]
I'm trying to use a ViewSet from adrf, but the 'get' handler is being mapped to the (non-async) 'retrieve' method from the non-adrf viewset mixin. Likewise for the other handlers. I'm curious why the coroutines 'aretrieve', 'adelete', etc. were added instead of overriding the existing 'retrieve', 'delete', etc. methods. That way a SimpleRouter should be able to find them (without the user needing to provide a mapping to viewset.as_view()). Am I missing something? Thanks so much for this project, btw!

**Comment by tbeadle** [comment]
I have opened https://github.com/em1208/adrf/pull/45 as a possibility to address this.

**Comment by sreekumarvpl** [comment]
Even I faced this issue. I was trying to override aretrieve method in viewset and was not working at all, then I found that it is mapped to sync version retrieve instead of aretrieve.

**Comment by em1208** [comment]
I merged https://github.com/em1208/adrf/pull/48 and I will make a new release.
