### ISSUE TITLE
Is it ready for production?

### ISSUE THREAD

**Issue by sparkshares** [em1208/adrf#50]
Hello team, 
I have build my web application on django, I am planning to use async functionalities, is it fine to use this package? 

Is this package ready for production purpose?
I have my backend api on drf, and it currently handles around 50k daily api request, and I want to optimize the performance so I am planning to switch to async.

Please tell me your though on this;

**Comment by em1208** [comment]
Hello @sparkshares, you can test `adrf` and see if it works for your use case. `adrf` can be used in production, you can check the code yourself and you can make any change to suit your specific needs. 50k requests per day is not a huge number so I don't expect any scaling problem. If you face any bug please open an issue in github with the steps to reproduce the problem.

**Comment by sparkshares** [comment]
Thank you @em1208 for a great tool, 
I have a confusion if you can clear it to me. 

My project structure looks like this: 

 url > to views > to service > to serializer > returns to service > returns to view > returns a response.

here is view = 
![image](https://github.com/user-attachments/assets/b3417b5b-ac39-41ac-9eed-c65ea9702c0b)


here is service = 
![image](https://github.com/user-attachments/assets/95e4ea9b-472d-4354-abd3-0fa58c3956ed)

here is serializer = 
![image](https://github.com/user-attachments/assets/4421d2ab-3885-4434-bf07-acbb4bb09bd4)


Is it the right way of using it? 
If you can help me with better optimization would be great!
