### ISSUE TITLE
add viewsets action decorators.

### ISSUE THREAD

**Issue by abdoohossamm** [em1208/adrf#6]

**Comment by em1208** [comment]
@abdoohossamm Async viewset support has been added on the latest release 0.1.1. I'm closing this issue.

**Comment by mikedvinci90** [comment]
@em1208  Request was for "action" decorator mentioned here: https://www.django-rest-framework.org/api-guide/viewsets/#marking-extra-actions-for-routing.
Do you have any ideas for that?

**Comment by tasawernawaz** [comment]
@em1208 I tried to add a custom action in `viewset`, it works only when `detail=False` 🤔 when I tried to make it `detail=True` it always throws `405 Method not allowed`, mo matter whatever method I listed down as `methods=['post', 'get', 'delete']`. Nothing works :(

@mikedvinci90 did you find any solution?
